config/routes.rb
Futbol::Application.routes.draw do
  
  root :to => "home#index"
  
  get "home/index"
  get "home/login"
  get "home/logout"
  get "home/signup"
  get "home/about"

  get "home/add_user_to_match"
  get "home/cancel_player_to_match"
  get "home/confirm_player_to_match"
  get "home/new_match"
  get "home/edit_match"
  get "home/edit_user"
  get "users/list"

  match "users/login", :to => "users#login"
  match "matches/new_match", :to => "matches#new_match"
  resources :users
  resources :matches
    

end

app/models/match.rb
class Match < ActiveRecord::Base
  has_many :players
  validates_presence_of :name, :on => :create, :message => "name can't be blank"
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :match
  belongs_to :user
end

app/models/session_bag.rb
class SessionBag
  
  def self.get_current_user(session)
    User.find_by_id(session[:current_user])
  end
  
  def self.set_current_user(session, current_user)
    session[:current_user] = current_user.id
  end
  
  def self.clean_current_user(session)
    session[:current_user] = nil
  end
  
  def self.set_error(flash, message)
    flash[:error] = message
  end
  
  def self.get_error(flash)
    flash[:error]
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :players
  validates_presence_of :name, :message => "name can't be blank"
  validates_length_of :name, :minimum => 2, :too_short => "name should have at least 2 characters"
  validates_uniqueness_of :name, :message => "user already exists"
  validates_presence_of :email, :message => "email can't be blank"
  validates_length_of :email, :minimum => 6, :too_short => "email address too short"
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create, :message => "email address is invalid"
  validates_uniqueness_of :email, :message => "email already exists"
  validates_presence_of :password, :message => "password can't be blank"
  validates_confirmation_of :password, :message => "password should match confirmation"
  validates_length_of :password, :minimum => 3, :too_short => "password should have at least 3 characters"
  
  def admin?
    self.name == "admin"
  end
  
  def score
    confirmed = 0.0
    canceled = 0.0
    
    Player.find(:all, :conditions => ["user_id = ?", self.id]).each do |p|
      confirmed +=1.0 if p.confirm
      canceled +=1.0 if p.cancel
      canceled +=2.0 if !p.cancel && !p.confirm 
    end

    if (confirmed + canceled) != 0
      confirmed - canceled / Match.count 
    else 
      0 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :require_login
  
  def require_login
    redirect_to root_url if !SessionBag.get_current_user(session)  
  end
  
  def require_admin
    redirect_to root_url if !SessionBag.get_current_user(session) || !SessionBag.get_current_user(session).admin?  
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :require_login, :only => [:index, :login, :signup, :about]
    
  def index
    @user = SessionBag.get_current_user(session)
    @match = Match.last
    @player = @match.players.find_by_user_id(@user.id) if @user
    @players = Player.find(:all, :conditions => ["match_id = ?", @match.id], :order => "score desc")
  end
  
  def login
    @user = User.new
  end
  
  def logout
    SessionBag.clean_current_user(session)
    redirect_to root_url
  end
  
  def signup
    @user = User.new
  end
  
  def about
  end
  
  def add_user_to_match
    match = Match.last
    user = SessionBag.get_current_user(session)

    if !Player.find_by_user_id_and_match_id(user.id, match.id)
      player = Player.new
      player.user = user
      player.score = user.score
      user.players << player
      match.players << player
      match.save
    end
    
    redirect_to root_url
  end
  
  def confirm_player_to_match
    set_player_confirmation(Player.find(params[:player]), true)
  end
  
  def cancel_player_to_match
    set_player_confirmation(Player.find(params[:player]), false)
  end

  def new_match
    @match = Match.new
  end
  
  def edit_match
    @match = Match.find(params[:match])
  end

  def edit_user
    @user = User.find(params[:user])
  end
  
  private
  def set_player_confirmation(player, status)
    player.confirm = status
    player.cancel = !status
    player.save
    
    redirect_to root_url
  end
  
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_filter :require_admin
  
  def new_match
    match = Match.new(params[:match])
  
    if !match.save
      SessionBag.set_error(flash, match.errors.first[1])
    end
  
    redirect_to root_url
  end

  def update
    match = Match.find(params[:id])
  
    if !match.update_attributes(params[:match])
      SessionBag.set_error(flash, match.errors.first[1])
    end
  
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin
  skip_before_filter :require_login, :only => [:create, :login]
  skip_before_filter :require_admin, :only => [:create, :login, :update]
  
  def create
    user = User.new(params[:user])

    if user.save
      SessionBag.set_current_user(session, user)
    else
      SessionBag.set_error(flash, user.errors.first[1])
    end

    redirect_to root_url
  end
  
  def update
    user = User.find(params[:id])
    
    if !user.update_attributes(params[:user])
      SessionBag.set_error(flash, user.errors.first[1])
    end
  
    redirect_to root_url
  end
  
  def login
    user = User.new(params[:user])
    user = User.find_by_name_and_password(user.name, user.password)
    
    SessionBag.set_current_user(session, user) if user
    SessionBag.set_error(flash, "login fail") if !user

    redirect_to root_url
  end
  
  def list
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def is_user_logged
    !@user.nil?
  end
  
  def is_admin_logged            
    is_user_logged && @user.admin?
  end

  def is_user_registered_and_match_available
     !@match.closed && @user && !@player
  end
end

app/views/home/about.html.erb
<div class="span-24 backwhite shadow">
<br />
<fieldset>
	<legend>About</legend>
	<p>
		<strong>Jodeart Mindworks</strong> proudly brings to you this fantastic application!
	</p>
	<p>
		<%= button_to "Back", :controller => "home", :action => "index" %>
	</p>
      </fieldset>
</div>

app/views/home/edit_match.html.erb
<div class="span-24 backwhite shadow">
<br />
<%= form_for @match do |f| %>
<fieldset>
	<legend>Edit Match</legend>
	<p>
		<%= f.label :name %> <br /> 
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.check_box :require_confirmation %> <%= f.label :require_confirmation %>
		<%= f.check_box :closed %> <%= f.label :closed %>
	</p>
	<p>
		<%= f.submit "Submit", :disable_with => "..." %>
		<input name="Back" type="button" value="Back" onClick="javascript:history.go(-1);"/>
	</p>
</fieldset>
<% end %>
<script language="javascript">
$(document).ready(function() {
  $('#match_name').focus();
});
</script>
</div>

app/views/home/edit_user.html.erb
<div class="span-24 backwhite shadow">
<br />
<%= form_for @user do |f| %>
<fieldset>
	<legend>Profile for [<%= @user.name %>]</legend>
	<p>
		<%= f.label :email %> <br />
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %> <br />
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %> <br />
		<%= f.password_field :password_confirmation %>
	</p>
	<p>
		<%= f.submit "Submit", :disable_with => "..." %>
		<input name="Back" type="button" value="Back" onClick="javascript:history.go(-1);"/>
	</p>
</fieldset>
<% end %>
<script language="javascript">
$(document).ready(function() {
  $('#user_email').focus();
});
</script>
</div>

app/views/home/index.html.erb
<div class="span-24">
<div class="button-container">
  <%= link_to("[#{@user.name}]", home_edit_user_path(:user => (@user.id)), class: "button pill icon user") if is_user_logged %>
  <div class="button-group">
    <%= link_to "Login", { :controller => "home", :action => "login" }, class: "button pill" %>
    <%= link_to "Signup", { :controller => "home", :action => "signup"}, class: "button pill" %> 
    <%= link_to "Logout", { :controller => "home", :action => "logout" }, class: "button pill" %>
  </div>
  <div class="button-group minor-group">
    <%= link_to "About", { :controller => "home", :action => "about" }, class: "button pill" %>
    <%= mail_to "luis.capra@gmail.com", "Feedback", :encode => "javascript", class: "button pill icon mail" if !is_admin_logged %>	
  </div>
  <div class="button-group">
    <%= link_to("Users", users_list_path, class: "button pill") if is_admin_logged %>
    <%= link_to("New Match", { :controller => "home", :action => "new_match" }, class: "button pill") if is_admin_logged %>
  </div>
</div>
</div>
<div class="prepend-top append-bottom span-24 last backwhite shadow">
<br />
<br />
<% if @match %>
<% position = 0 %>
<table border="0" cellspacing="0" cellpadding="0">
	<caption>
		<em>
			Current match: "<b><%= @match.name %></b>"
			<%="(closed)" if @match.closed %>
		</em>
		<br />
                <%= link_to "Add me!", { :controller => "home", :action => "add_user_to_match" }, class: "button" if is_user_registered_and_match_available %>
		<%= link_to "Edit", home_edit_match_path(:match => @match.id), class: "button" if is_admin_logged %>
	</caption>
	<thead>
		<tr>
			<th class="span-4">Position</th>
			<th class="span-4">Score</th>
			<th class="span-4">Name</th>
			<th class="span-4">Status</th>
			<% if @match.require_confirmation %>
			<th class="span-4">Actions</th>
			<% end %>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="2">Total: <%= "#{@match.players.count}" %></td>
		</tr>
	</tfoot>
	<tbody>
		<% @players.each_with_index do |p, index| %>
		<tr>
			<td><%= index + 1 %></td>
			<td><%= p.score.round(1) %></td>
			<td><%= p.user.name %></td>
			<td>
				<%= "CONFIRMED" if p.confirm %> 
				<%= "CANCELLED" if p.cancel %> 
				<%= "NEW" if !p.confirm && !p.cancel %> 
			</td>
			<%if @match.require_confirmation %>
			<td>
				<% if (!p.confirm && !p.cancel && @user && !@user.admin? && p.user == @user) || (@user && @user.admin?) %>
                                <div class="button-group">
				<%= link_to "Confirm", home_confirm_player_to_match_path(:player => p), class: "button icon approve" if @user && !p.confirm%>
                                <%= link_to "Cancel", home_cancel_player_to_match_path(:player => p), class: "button danger icon remove" if @user && !p.cancel  %>
                              </div>
				<% end %>
			</td>
			<% end %>
		</tr>
		<% end %>
	</tbody>
</table>
<% end %>

app/views/home/login.html.erb
<div class="span-24 backwhite">
<br />
<%= form_for @user, :url => users_login_path(@user) do |f| %>
<fieldset>
	<legend>Login</legend>
	<p>
		<%= f.label :name %> <br /> 
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :password %> <br />
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.submit "Submit" %>
		<input name="Back" type="button" value="Back" onClick="javascript:history.go(-1);"/>
	</p>
</fieldset>
<% end %>
<script language="javascript">
$(document).ready(function() {
  $('#user_name').focus();
});
</script>
</div>

app/views/home/new_match.html.erb
<br />
<%= form_for @match, :url => matches_new_match_path(@match) do |f| %>
<fieldset>
	<legend>New Match</legend>
	<p>
		<%= f.label :name %> <br /> 
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.submit "Submit" %>
		<input name="Back" type="button" value="Back" onClick="javascript:history.go(-1);"/>
	</p>
</fieldset>
<% end %>
<script language="javascript">
$(document).ready(function() {
  $('#match_name').focus();
});
</script>

app/views/home/signup.html.erb
<div class="span-24 backwhite shadow">
<br />
<%= form_for @user do |f| %>
<fieldset>
	<legend>Signup</legend>
	<p>
		<%= f.label :name %> <br />
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %> <br />
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %> <br />
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %> <br />
		<%= f.password_field :password_confirmation %>
	</p>
	<p>
		<%= f.submit "Submit", :disable_with => "..." %>
		<input name="Back" type="button" value="Back" onClick="javascript:history.go(-1);"/>
	</p>
</fieldset>
<% end %>
<script language="javascript">
$(document).ready(function() {
  $('#user_name').focus();
});
</script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>La Cancha de tu hermana!</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= stylesheet_link_tag    "screen", :media => "screen, projection" %>
	<%= stylesheet_link_tag    "print", :media => "print" %>
	<!–[if IE]><%= stylesheet_link_tag    "ie", :media => "screen, projection" %><![endif]–>
  	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
  <div class="backgreen shade">
	<div class="container">
          <div class="prepend-1 span-23">
		<h2>Futbol</h2>
	  </div>
	</div>
  </div>
        <br/>
    <% if SessionBag.get_error(flash) %>
    <div class="container error">
      <%= SessionBag.get_error(flash) %>
    </div>
    <% end %>
    <div class="container ">
		<%= yield %>
    </div>
</body>
</html>

app/views/users/list.html.erb
<div class="span-24 backwhite shadow">
<table border="0" cellspacing="0" cellpadding="0">
	<caption><em>User's List</em></caption>
	<thead>
		<tr>
			<th class="span-4">Score</th>
			<th class="span-4">Email</th>
			<th class="span-4">Name</th>
			<th class="span-4 last">Password</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="2">Total: <%= "#{@users.count}" %></td>
		</tr>
	</tfoot>
	<tbody>
		<% @users.each do |u| %>
		<tr>
			<td><%= u.score.round(1) %></td>
			<td><%= u.email %></td>
			<td><%= u.name %></td>
			<td><%= u.password %></td>
		</tr>
		<% end if @users %>
	</tbody>
</table>
<p>
	<%= button_to "Back", :controller => "home", :action => "index" %>
        </p>
      </div>